# Generated by Django 4.2.5 on 2023-09-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitentry',
            options={'verbose_name_plural': 'Habit entries'},
        ),
        migrations.AlterModelOptions(
            name='habitstatus',
            options={'verbose_name_plural': 'Habit statuses'},
        ),
        migrations.AddField(
            model_name='habitentry',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.habitstatus'),
        ),
        migrations.AddField(
            model_name='habittarget',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.habitstatus'),
        ),
    ]
