# Generated by Django 4.2.5 on 2023-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_habitentry_options_alter_habitstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittype',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
